/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home.java
 *
 * Created on 5 févr. 2011, 18:26:20
 */

package org.meditenance.centre.ui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import org.meditenance.centre.DAO.ClientDAO;
import org.meditenance.centre.DAO.EmployeeDAO;
import org.meditenance.centre.DAO.model.DAO;
import org.meditenance.centre.DAO.model.FurnitureDAO;
import org.meditenance.centre.DAO.model.InterventionDAO;
import org.meditenance.centre.DAO.model.PieceDAO;
import org.meditenance.centre.domain.Client;
import org.meditenance.centre.domain.Employee;
import org.meditenance.centre.domain.Furniture;
import org.meditenance.centre.domain.Intervention;

/**
 *
 * @author Talus
 */
public class Home extends javax.swing.JFrame {
  // -- DAOs
  private DAO clientDAO = new ClientDAO();
  private DAO employeeDAO = new EmployeeDAO();
  private InterventionDAO interventionDAO = new org.meditenance.centre.DAO.InterventionDAO();
  private FurnitureDAO furnitureDAO = new org.meditenance.centre.DAO.FurnitureDAO();
  private PieceDAO pieceDAO = new org.meditenance.centre.DAO.PieceDAO();

  /** Creates new form Home */
  public Home() {
    DefaultComboBoxModel clientModel = new DefaultComboBoxModel(this.clientDAO.getAll().toArray());

    this.initComponents();

    // -- Clients
    this.clientsList.setModel(new DefaultListModel());
    this.fillList(this.clientDAO.getAll(), this.clientsList);

    // -- Employés
    this.employeesList.setModel(new DefaultListModel());
    this.fillList(this.employeeDAO.getAll(), this.employeesList);
    this.employeeRole.setModel(new DefaultComboBoxModel(Role.values()));
    this.employeeRole.setSelectedIndex(-1);

    // -- Matériel
    this.furnituresList.setModel(new DefaultListModel());
    this.fillList(this.furnitureDAO.getAll(), this.furnituresList);
    this.furnitureClient.setModel(clientModel);
    this.furnitureClient.setSelectedIndex(-1);

    // -- Interventions
    this.interventionsList.setModel(new DefaultListModel());
    this.fillList(this.interventionDAO.getAll(), this.interventionsList);
    this.interventionClient.setModel(clientModel);
    this.interventionEmployee.setModel(new DefaultComboBoxModel(this.employeeDAO.getAll().toArray()));
    this.interventionType.setModel(new DefaultComboBoxModel(Type.values()));
    this.interventionClient.setSelectedIndex(-1);
    this.interventionEmployee.setSelectedIndex(-1);
    this.interventionType.setSelectedIndex(-1);

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    PieceTab = new javax.swing.JTabbedPane();
    ClientTab = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    clientsList = new javax.swing.JList();
    clientAction = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    clientLastName = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    clientFirstName = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    clientAddress = new javax.swing.JTextField();
    clientButton = new javax.swing.JButton();
    cancelClient = new javax.swing.JButton();
    clientSuppr = new javax.swing.JButton();
    FurnitureTab = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    furnituresList = new javax.swing.JList();
    furnitureAction = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    furnitureRef = new javax.swing.JTextField();
    furnitureBrand = new javax.swing.JTextField();
    furnitureClient = new javax.swing.JComboBox();
    furnitureLastIntervention = new com.toedter.calendar.JDateChooser();
    furnitureButton = new javax.swing.JButton();
    furnitureCancel = new javax.swing.JButton();
    furnitureSuppr = new javax.swing.JButton();
    EmployeeTab = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    employeesList = new javax.swing.JList();
    employeeAction = new javax.swing.JLabel();
    employeeBirthDate = new com.toedter.calendar.JDateChooser();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    employeeCancel = new javax.swing.JButton();
    employeeButton = new javax.swing.JButton();
    employeeSuppr = new javax.swing.JButton();
    employeeSpe = new javax.swing.JTextField();
    employeeRole = new javax.swing.JComboBox();
    employeeAddress = new javax.swing.JTextField();
    employeeName = new javax.swing.JTextField();
    employeeFirstName = new javax.swing.JTextField();
    InterventionTab = new javax.swing.JPanel();
    jLabel13 = new javax.swing.JLabel();
    jScrollPane4 = new javax.swing.JScrollPane();
    interventionsList = new javax.swing.JList();
    interventionAction = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    jLabel20 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    jLabel22 = new javax.swing.JLabel();
    jLabel23 = new javax.swing.JLabel();
    jLabel24 = new javax.swing.JLabel();
    jScrollPane5 = new javax.swing.JScrollPane();
    interventionAnnotations = new javax.swing.JTextArea();
    interventionEmployee = new javax.swing.JComboBox();
    interventionClient = new javax.swing.JComboBox();
    interventionEnd = new com.toedter.calendar.JDateChooser();
    interventionType = new javax.swing.JComboBox();
    interventionCost = new javax.swing.JTextField();
    interventionCancel = new javax.swing.JButton();
    interventionButton = new javax.swing.JButton();
    interventionSuppr = new javax.swing.JButton();
    interventionBegin = new com.toedter.calendar.JDateChooser();
    jPanel1 = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(503, 458));
    setName("UI"); // NOI18N
    setResizable(false);

    PieceTab.setName("PieceTab"); // NOI18N

    ClientTab.setMinimumSize(new java.awt.Dimension(498, 430));
    ClientTab.setName("ClientTab"); // NOI18N

    jLabel1.setText("Clients");
    jLabel1.setName("jLabel1"); // NOI18N

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    clientsList.setName("clientsList"); // NOI18N
    clientsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        clientsListValueChanged(evt);
      }
    });
    jScrollPane1.setViewportView(clientsList);

    clientAction.setText("Ajout d'un client");
    clientAction.setName("clientAction"); // NOI18N

    jLabel3.setText("Nom");
    jLabel3.setName("jLabel3"); // NOI18N

    clientLastName.setName("clientLastName"); // NOI18N

    jLabel4.setText("Prénom");
    jLabel4.setName("jLabel4"); // NOI18N

    clientFirstName.setName("clientFirstName"); // NOI18N

    jLabel5.setText("Addresse");
    jLabel5.setName("jLabel5"); // NOI18N

    clientAddress.setName("clientAddress"); // NOI18N

    clientButton.setText("Ajouter");
    clientButton.setName("clientButton"); // NOI18N
    clientButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clientButtonActionPerformed(evt);
      }
    });

    cancelClient.setText("Annuler");
    cancelClient.setName("cancelClient"); // NOI18N
    cancelClient.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelClientActionPerformed(evt);
      }
    });

    clientSuppr.setText("Supprimer");
    clientSuppr.setEnabled(false);
    clientSuppr.setName("clientSuppr"); // NOI18N
    clientSuppr.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clientSupprActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout ClientTabLayout = new javax.swing.GroupLayout(ClientTab);
    ClientTab.setLayout(ClientTabLayout);
    ClientTabLayout.setHorizontalGroup(
      ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ClientTabLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientTabLayout.createSequentialGroup()
              .addGap(22, 22, 22)
              .addComponent(clientAction))
            .addGroup(ClientTabLayout.createSequentialGroup()
              .addGap(18, 18, 18)
              .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClientTabLayout.createSequentialGroup()
                  .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                  .addGap(18, 18, 18)
                  .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(clientLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(clientAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                .addGroup(ClientTabLayout.createSequentialGroup()
                  .addComponent(cancelClient)
                  .addGap(31, 31, 31)
                  .addComponent(clientSuppr)))
              .addContainerGap()))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientTabLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(clientButton)
            .addGap(21, 21, 21))))
    );
    ClientTabLayout.setVerticalGroup(
      ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ClientTabLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(clientAction))
        .addGap(18, 18, 18)
        .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(ClientTabLayout.createSequentialGroup()
            .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(clientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(33, 33, 33)
            .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4)
              .addComponent(clientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(29, 29, 29)
            .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel5)
              .addComponent(clientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(48, 48, 48)
            .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(clientButton)
              .addComponent(cancelClient)
              .addComponent(clientSuppr)))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(195, 195, 195))
    );

    PieceTab.addTab("Clients", ClientTab);

    FurnitureTab.setName("FurnitureTab"); // NOI18N

    jLabel6.setText("Liste du Matériel");
    jLabel6.setName("jLabel6"); // NOI18N

    jScrollPane3.setName("jScrollPane3"); // NOI18N

    furnituresList.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    furnituresList.setName("furnituresList"); // NOI18N
    furnituresList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        furnituresListValueChanged(evt);
      }
    });
    jScrollPane3.setViewportView(furnituresList);

    furnitureAction.setText("Ajout d'un matériel");
    furnitureAction.setName("furnitureAction"); // NOI18N

    jLabel14.setText("Référence");
    jLabel14.setName("jLabel14"); // NOI18N

    jLabel15.setText("Marque");
    jLabel15.setName("jLabel15"); // NOI18N

    jLabel16.setText("Client");
    jLabel16.setName("jLabel16"); // NOI18N

    jLabel17.setText("Dernière Intervention");
    jLabel17.setName("jLabel17"); // NOI18N

    furnitureRef.setName("furnitureRef"); // NOI18N

    furnitureBrand.setName("furnitureBrand"); // NOI18N

    furnitureClient.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    furnitureClient.setName("furnitureClient"); // NOI18N

    furnitureLastIntervention.setDateFormatString("dd/MM/yyyy");
    furnitureLastIntervention.setName("furnitureLastIntervention"); // NOI18N

    furnitureButton.setText("Ajouter");
    furnitureButton.setName("furnitureButton"); // NOI18N
    furnitureButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        furnitureButtonActionPerformed(evt);
      }
    });

    furnitureCancel.setText("Annuler");
    furnitureCancel.setName("furnitureCancel"); // NOI18N
    furnitureCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        furnitureCancelActionPerformed(evt);
      }
    });

    furnitureSuppr.setText("Supprimer");
    furnitureSuppr.setEnabled(false);
    furnitureSuppr.setName("furnitureSuppr"); // NOI18N
    furnitureSuppr.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        furnitureSupprActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout FurnitureTabLayout = new javax.swing.GroupLayout(FurnitureTab);
    FurnitureTab.setLayout(FurnitureTabLayout);
    FurnitureTabLayout.setHorizontalGroup(
      FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FurnitureTabLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(FurnitureTabLayout.createSequentialGroup()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(29, 29, 29)
            .addGroup(FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(FurnitureTabLayout.createSequentialGroup()
                .addGroup(FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel14)
                  .addComponent(jLabel15)
                  .addComponent(jLabel16)
                  .addComponent(jLabel17))
                .addGap(28, 28, 28)
                .addGroup(FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(furnitureLastIntervention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(furnitureClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(furnitureBrand)
                  .addComponent(furnitureRef, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FurnitureTabLayout.createSequentialGroup()
                .addComponent(furnitureCancel)
                .addGap(18, 18, 18)
                .addComponent(furnitureSuppr)
                .addGap(18, 18, 18)
                .addComponent(furnitureButton)
                .addGap(8, 8, 8))))
          .addGroup(FurnitureTabLayout.createSequentialGroup()
            .addComponent(jLabel6)
            .addGap(103, 103, 103)
            .addComponent(furnitureAction)))
        .addContainerGap())
    );
    FurnitureTabLayout.setVerticalGroup(
      FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(FurnitureTabLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(furnitureAction))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(FurnitureTabLayout.createSequentialGroup()
            .addGap(8, 8, 8)
            .addGroup(FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel14)
              .addComponent(furnitureRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(27, 27, 27)
            .addGroup(FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel15)
              .addComponent(furnitureBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel16)
              .addComponent(furnitureClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(29, 29, 29)
            .addGroup(FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(furnitureLastIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel17))
            .addGap(42, 42, 42)
            .addGroup(FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(furnitureCancel)
              .addComponent(furnitureButton)
              .addComponent(furnitureSuppr))))
        .addContainerGap(151, Short.MAX_VALUE))
    );

    PieceTab.addTab("Matériel", FurnitureTab);

    EmployeeTab.setName("EmployeeTab"); // NOI18N

    jLabel2.setText("Liste des Employés");
    jLabel2.setName("jLabel2"); // NOI18N

    jScrollPane2.setName("jScrollPane2"); // NOI18N

    employeesList.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    employeesList.setName("employeesList"); // NOI18N
    employeesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        employeesListValueChanged(evt);
      }
    });
    jScrollPane2.setViewportView(employeesList);

    employeeAction.setText("Ajout d'un employé");
    employeeAction.setName("employeeAction"); // NOI18N

    employeeBirthDate.setDateFormatString("dd/MM/yyyy");
    employeeBirthDate.setMaxSelectableDate(new java.util.Date(253370764864000L));
    employeeBirthDate.setName("employeeBirthDate"); // NOI18N

    jLabel7.setText("Prénom");
    jLabel7.setName("jLabel7"); // NOI18N

    jLabel8.setText("Nom");
    jLabel8.setName("jLabel8"); // NOI18N

    jLabel9.setText("Addresse");
    jLabel9.setName("jLabel9"); // NOI18N

    jLabel10.setText("Rôle");
    jLabel10.setName("jLabel10"); // NOI18N

    jLabel11.setText("Spécialisation");
    jLabel11.setName("jLabel11"); // NOI18N

    jLabel12.setText("Date de Naissance");
    jLabel12.setName("jLabel12"); // NOI18N

    employeeCancel.setText("Annuler");
    employeeCancel.setName("employeeCancel"); // NOI18N
    employeeCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        employeeCancelActionPerformed(evt);
      }
    });

    employeeButton.setText("Ajouter");
    employeeButton.setName("employeeButton"); // NOI18N
    employeeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        employeeButtonActionPerformed(evt);
      }
    });

    employeeSuppr.setText("Supprimer");
    employeeSuppr.setEnabled(false);
    employeeSuppr.setName("employeeSuppr"); // NOI18N
    employeeSuppr.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        employeeSupprActionPerformed(evt);
      }
    });

    employeeSpe.setName("employeeSpe"); // NOI18N

    employeeRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    employeeRole.setName("employeeRole"); // NOI18N

    employeeAddress.setName("employeeAddress"); // NOI18N

    employeeName.setName("employeeName"); // NOI18N

    employeeFirstName.setName("employeeFirstName"); // NOI18N

    javax.swing.GroupLayout EmployeeTabLayout = new javax.swing.GroupLayout(EmployeeTab);
    EmployeeTab.setLayout(EmployeeTabLayout);
    EmployeeTabLayout.setHorizontalGroup(
      EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(EmployeeTabLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(EmployeeTabLayout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(101, 101, 101)
            .addComponent(employeeAction))
          .addGroup(EmployeeTabLayout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(40, 40, 40)
            .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(EmployeeTabLayout.createSequentialGroup()
                .addComponent(employeeCancel)
                .addGap(18, 18, 18)
                .addComponent(employeeSuppr)
                .addGap(18, 18, 18)
                .addComponent(employeeButton))
              .addGroup(EmployeeTabLayout.createSequentialGroup()
                .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel12)
                  .addComponent(jLabel11)
                  .addComponent(jLabel10)
                  .addComponent(jLabel9)
                  .addComponent(jLabel8)
                  .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(employeeFirstName)
                  .addComponent(employeeName)
                  .addComponent(employeeAddress)
                  .addComponent(employeeRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(employeeSpe)
                  .addComponent(employeeBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))))
        .addContainerGap(81, Short.MAX_VALUE))
    );
    EmployeeTabLayout.setVerticalGroup(
      EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(EmployeeTabLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(employeeAction))
        .addGap(18, 18, 18)
        .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(EmployeeTabLayout.createSequentialGroup()
            .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel7)
              .addComponent(employeeFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel8)
              .addComponent(employeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel9)
              .addComponent(employeeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel10)
              .addComponent(employeeRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel11)
              .addComponent(employeeSpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(employeeBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel12))
            .addGap(33, 33, 33)
            .addGroup(EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(employeeCancel)
              .addComponent(employeeSuppr)
              .addComponent(employeeButton)))
          .addComponent(jScrollPane2))
        .addContainerGap(142, Short.MAX_VALUE))
    );

    PieceTab.addTab("Employés", EmployeeTab);

    InterventionTab.setName("InterventionTab"); // NOI18N

    jLabel13.setText("Liste des Interventions");
    jLabel13.setName("jLabel13"); // NOI18N

    jScrollPane4.setName("jScrollPane4"); // NOI18N

    interventionsList.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    interventionsList.setName("interventionsList"); // NOI18N
    interventionsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        interventionsListValueChanged(evt);
      }
    });
    jScrollPane4.setViewportView(interventionsList);

    interventionAction.setText("Ajout d'une Intervention");
    interventionAction.setName("interventionAction"); // NOI18N

    jLabel18.setText("Nature");
    jLabel18.setName("jLabel18"); // NOI18N

    jLabel19.setText("Date de Début");
    jLabel19.setName("jLabel19"); // NOI18N

    jLabel20.setText("Date de Fin");
    jLabel20.setName("jLabel20"); // NOI18N

    jLabel21.setText("Client");
    jLabel21.setName("jLabel21"); // NOI18N

    jLabel22.setText("Employé");
    jLabel22.setName("jLabel22"); // NOI18N

    jLabel23.setText("Coût");
    jLabel23.setName("jLabel23"); // NOI18N

    jLabel24.setText("Remarques");
    jLabel24.setName("jLabel24"); // NOI18N

    jScrollPane5.setName("jScrollPane5"); // NOI18N

    interventionAnnotations.setColumns(20);
    interventionAnnotations.setLineWrap(true);
    interventionAnnotations.setRows(5);
    interventionAnnotations.setName("interventionAnnotations"); // NOI18N
    jScrollPane5.setViewportView(interventionAnnotations);

    interventionEmployee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    interventionEmployee.setName("interventionEmployee"); // NOI18N

    interventionClient.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    interventionClient.setName("interventionClient"); // NOI18N

    interventionEnd.setDateFormatString("dd/MM/yyyy");
    interventionEnd.setName("interventionEnd"); // NOI18N

    interventionType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    interventionType.setName("interventionType"); // NOI18N

    interventionCost.setName("interventionCost"); // NOI18N

    interventionCancel.setText("Annuler");
    interventionCancel.setName("interventionCancel"); // NOI18N
    interventionCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        interventionCancelActionPerformed(evt);
      }
    });

    interventionButton.setText("Ajouter");
    interventionButton.setName("interventionButton"); // NOI18N
    interventionButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        interventionButtonActionPerformed(evt);
      }
    });

    interventionSuppr.setText("Supprimer");
    interventionSuppr.setEnabled(false);
    interventionSuppr.setName("interventionSuppr"); // NOI18N
    interventionSuppr.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        interventionSupprActionPerformed(evt);
      }
    });

    interventionBegin.setDateFormatString("dd/MM/yyyy");
    interventionBegin.setName("interventionBegin"); // NOI18N

    javax.swing.GroupLayout InterventionTabLayout = new javax.swing.GroupLayout(InterventionTab);
    InterventionTab.setLayout(InterventionTabLayout);
    InterventionTabLayout.setHorizontalGroup(
      InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InterventionTabLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(InterventionTabLayout.createSequentialGroup()
            .addComponent(jLabel13)
            .addGap(92, 92, 92)
            .addComponent(interventionAction))
          .addGroup(InterventionTabLayout.createSequentialGroup()
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(InterventionTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel20)
                  .addComponent(jLabel19)
                  .addComponent(jLabel21)
                  .addComponent(jLabel22)
                  .addComponent(jLabel24)
                  .addComponent(jLabel18)
                  .addComponent(jLabel23)))
              .addGroup(InterventionTabLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(interventionCancel)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(InterventionTabLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(jScrollPane5)
                  .addComponent(interventionType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(interventionEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(interventionClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(interventionEmployee, 0, 178, Short.MAX_VALUE)
                  .addComponent(interventionBegin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(interventionCost, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
              .addGroup(InterventionTabLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(interventionSuppr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(interventionButton)))))
        .addContainerGap())
    );
    InterventionTabLayout.setVerticalGroup(
      InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InterventionTabLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel13)
          .addComponent(interventionAction))
        .addGap(18, 18, 18)
        .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(InterventionTabLayout.createSequentialGroup()
            .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel18)
              .addComponent(interventionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(InterventionTabLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(18, 18, 18))
              .addGroup(InterventionTabLayout.createSequentialGroup()
                .addComponent(interventionCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)))
            .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel19)
              .addComponent(interventionBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(interventionEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(17, 17, 17)
            .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(interventionClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel21))
            .addGap(13, 13, 13)
            .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(interventionEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel22))
            .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InterventionTabLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(interventionCancel)
                  .addComponent(interventionSuppr)
                  .addComponent(interventionButton))
                .addContainerGap())
              .addGroup(InterventionTabLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addContainerGap())))
          .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    PieceTab.addTab("Interventions", InterventionTab);

    jPanel1.setName("jPanel1"); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 554, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 451, Short.MAX_VALUE)
    );

    PieceTab.addTab("Pièces", jPanel1);

    PieceTab.setSelectedComponent(ClientTab);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(PieceTab, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(PieceTab)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cancelClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelClientActionPerformed
    this.clearClientSelection();
}//GEN-LAST:event_cancelClientActionPerformed

  private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
    Client cli = null;

    if (this.clientLastName.getText().isEmpty() || this.clientFirstName.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Les champs pour le nom et le prénom du client sont obligatoires", "Erreur", JOptionPane.ERROR_MESSAGE);
      return;
    }

    cli = this.clientSuppr.isEnabled() ? (Client) this.clientsList.getSelectedValue() : new Client();

    cli.setFirstName(this.clientFirstName.getText());
    cli.setLastName(this.clientLastName.getText());
    cli.setAddress(this.clientAddress.getText());

    this.clientDAO.save(cli);
    this.clearClientSelection();
    this.fillList(this.clientDAO.getAll(), this.clientsList);

    if (!this.clientSuppr.isEnabled()) {
      ((DefaultComboBoxModel) this.furnitureClient.getModel()).addElement(cli);
    }

    return;
}//GEN-LAST:event_clientButtonActionPerformed

  private void clientsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_clientsListValueChanged
    Client c = (Client) this.clientsList.getSelectedValue();

    if (c != null) {
      this.clientSuppr.setEnabled(true);

      this.clientAddress.setText(c.getAddress());
      this.clientFirstName.setText(c.getFirstName());
      this.clientLastName.setText(c.getLastName());

      this.clientAction.setText("Edition du client n°" + c.getId());
      this.clientButton.setText("Editer");
    }
}//GEN-LAST:event_clientsListValueChanged

  private void employeeSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSupprActionPerformed
    Employee emp = (Employee) this.employeesList.getSelectedValue();

    if (emp != null && JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer l'employé " + emp + " ?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
      this.employeeDAO.remove(emp);
      this.clearEmployeeSelection();
      
      ((DefaultListModel) this.employeesList.getModel()).removeElement(emp);
    }
  }//GEN-LAST:event_employeeSupprActionPerformed

  private void clientSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientSupprActionPerformed
    Client cli = (Client) this.clientsList.getSelectedValue();

    if (cli != null && JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer le client " + cli + " ?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
      this.clientDAO.remove(cli);
      this.clearClientSelection();
      
      ((DefaultListModel) this.clientsList.getModel()).removeElement(cli);
      ((DefaultComboBoxModel) this.furnitureClient.getModel()).removeElement(cli);
    }
  }//GEN-LAST:event_clientSupprActionPerformed

  private void employeesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_employeesListValueChanged
    Employee emp = (Employee) this.employeesList.getSelectedValue();

    if (emp != null) {
      this.employeeAddress.setText(emp.getAddress());
      this.employeeBirthDate.setDate(emp.getBirthDate());
      this.employeeFirstName.setText(emp.getFirstName());
      this.employeeName.setText(emp.getLastName());
      this.employeeRole.setSelectedIndex(emp.getRole());
      this.employeeSpe.setText(emp.getSpecialization());

      this.employeeAction.setText("Edition de l'employé n°" + emp.getId());
      this.employeeButton.setText("Editer");
      this.employeeSuppr.setEnabled(true);
    }
  }//GEN-LAST:event_employeesListValueChanged

  private void employeeCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeCancelActionPerformed
    this.clearEmployeeSelection();
  }//GEN-LAST:event_employeeCancelActionPerformed

  private void employeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeButtonActionPerformed
    Employee emp = null;

    if (this.employeeName.getText().isEmpty() || this.employeeFirstName.getText().isEmpty() || this.employeeRole.getSelectedIndex() == -1) {
      JOptionPane.showMessageDialog(this, "Les champs pour le nom, le prénom et le rôle de l'employé sont obligatoires", "Erreur", JOptionPane.ERROR_MESSAGE);
      return;
    }

    emp = this.employeeSuppr.isEnabled() ? (Employee) this.employeesList.getSelectedValue() : new Employee();

    emp.setFirstName(this.employeeFirstName.getText());
    emp.setLastName(this.employeeName.getText());
    emp.setRole(this.employeeRole.getSelectedIndex());
    emp.setAddress(this.employeeAddress.getText());
    emp.setBirthDate(this.employeeBirthDate.getDate());
    emp.setSpecialization(this.employeeSpe.getText());

    this.employeeDAO.save(emp);
    this.clearEmployeeSelection();
    this.fillList(this.employeeDAO.getAll(), this.employeesList);

    return;
  }//GEN-LAST:event_employeeButtonActionPerformed

  private void furnituresListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_furnituresListValueChanged
    Furniture f = (Furniture) this.furnituresList.getSelectedValue();

    if (f != null) {
      this.furnitureSuppr.setEnabled(true);

      this.furnitureBrand.setText(f.getBrand());
      ((DefaultComboBoxModel) this.furnitureClient.getModel()).setSelectedItem(f.getClient());
      this.furnitureRef.setText(f.getRef());
      this.furnitureLastIntervention.setDate(f.getLastIntervention());
      
      this.furnitureAction.setText("Edition du matériel n°" + f.getId());
      this.furnitureButton.setText("Editer");
    }
  }//GEN-LAST:event_furnituresListValueChanged

  private void furnitureCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_furnitureCancelActionPerformed
    this.clearFurnitureSelection();
  }//GEN-LAST:event_furnitureCancelActionPerformed

  private void furnitureSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_furnitureSupprActionPerformed
    Furniture fur = (Furniture) this.furnituresList.getSelectedValue();

    if (fur != null && JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer le matériel " + fur + " ?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
      this.furnitureDAO.remove(fur);
      this.clearFurnitureSelection();

      ((DefaultListModel) this.furnituresList.getModel()).removeElement(fur);
    }
  }//GEN-LAST:event_furnitureSupprActionPerformed

  private void furnitureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_furnitureButtonActionPerformed
    Furniture fur = null;

    if (this.furnitureRef.getText().isEmpty() || this.furnitureBrand.getText().isEmpty() || this.furnitureClient.getSelectedIndex() == -1) {
      JOptionPane.showMessageDialog(this, "Les champs pour la marque, la référence et le client pour ce matériel sont obligatoires", "Erreur", JOptionPane.ERROR_MESSAGE);
      return;
    }

    fur = this.furnitureSuppr.isEnabled() ? (Furniture) this.furnituresList.getSelectedValue() : new Furniture();

    fur.setBrand(this.furnitureBrand.getText());
    fur.setRef(this.furnitureRef.getText());
    fur.setClient((Client) this.furnitureClient.getSelectedItem());
    fur.setLastIntervention(this.furnitureLastIntervention.getDate());

    this.furnitureDAO.save(fur);
    this.clearFurnitureSelection();
    this.fillList(this.furnitureDAO.getAll(), this.furnituresList);
  }//GEN-LAST:event_furnitureButtonActionPerformed

  private void interventionCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interventionCancelActionPerformed
    this.clearInterventionSelection();
  }//GEN-LAST:event_interventionCancelActionPerformed

  private void interventionSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interventionSupprActionPerformed
    Intervention intervention = (Intervention) this.interventionsList.getSelectedValue();

    if (intervention != null && JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer " + intervention + " ?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
      this.interventionDAO.remove(intervention);
      this.clearInterventionSelection();

      ((DefaultListModel) this.interventionsList.getModel()).removeElement(intervention);
    }
  }//GEN-LAST:event_interventionSupprActionPerformed

  private void interventionsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_interventionsListValueChanged
    Intervention i = (Intervention) this.interventionsList.getSelectedValue();

    if (i != null) {
      this.interventionSuppr.setEnabled(true);

      this.interventionAnnotations.setText(i.getAnnotations());
      this.interventionBegin.setDate(i.getBegin());
      this.interventionEnd.setDate(i.getEnd());
      this.interventionCost.setText(i.getCost().toString());
      ((DefaultComboBoxModel) this.interventionClient.getModel()).setSelectedItem(i.getClient());
      ((DefaultComboBoxModel) this.interventionEmployee.getModel()).setSelectedItem(i.getEmployee());
      this.interventionType.setSelectedIndex(i.getNature());

      this.interventionAction.setText("Edition de l'intervention n°" + i.getId());
      this.interventionButton.setText("Editer");
    }
  }//GEN-LAST:event_interventionsListValueChanged

  private void interventionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interventionButtonActionPerformed
    Intervention intervention = null;

    if (this.interventionBegin.getDate() == null || this.interventionType.getSelectedIndex() == -1 || this.interventionClient.getSelectedIndex() == -1) {
      JOptionPane.showMessageDialog(this, "Les champs pour la date / heure de début, le type, et le client pour une intervention sont obligatoires", "Erreur", JOptionPane.ERROR_MESSAGE);
      return;
    }

    if (!this.interventionCost.getText().isEmpty() && !this.isInt(this.interventionCost.getText())) {
      JOptionPane.showMessageDialog(this, "Entrez un coût valide pour une intervention donnée", "Erreur", JOptionPane.ERROR_MESSAGE);
      return;
    }

    intervention = this.interventionSuppr.isEnabled() ? (Intervention) this.interventionsList.getSelectedValue() : new Intervention();

    intervention.setAnnotations(this.interventionAnnotations.getText());
    intervention.setCost(this.interventionCost.getText().isEmpty() ? 0 : Integer.parseInt(this.interventionCost.getText()));
    intervention.setBegin(this.interventionBegin.getDate());
    intervention.setEnd(this.interventionEnd.getDate());

    if (this.interventionEmployee.getSelectedItem() != null) {
      intervention.setEmployee((Employee) this.interventionEmployee.getSelectedItem());
    }
    
    intervention.setClient((Client) this.interventionClient.getSelectedItem());
    intervention.setNature(this.interventionType.getSelectedIndex());

    this.interventionDAO.save(intervention);
    this.clearInterventionSelection();
    this.fillList(this.interventionDAO.getAll(), this.interventionsList);
  }//GEN-LAST:event_interventionButtonActionPerformed

  private void clearClientSelection() {
    this.clientAddress.setText("");
    this.clientLastName.setText("");
    this.clientFirstName.setText("");

    this.clientAction.setText("Ajout d'un client");
    this.clientButton.setText("Ajouter");
    this.clientSuppr.setEnabled(false);

    this.clientsList.clearSelection();
  }

  private void clearEmployeeSelection() {
    this.employeeAddress.setText("");
    this.employeeName.setText("");
    this.employeeFirstName.setText("");
    this.employeeSpe.setText("");
    this.employeeBirthDate.setDate(null);

    this.employeeAction.setText("Ajout d'un employé");
    this.employeeButton.setText("Ajouter");
    this.employeeSuppr.setEnabled(false);

    this.employeeRole.setSelectedIndex(-1);
    this.employeesList.clearSelection();
  }

  private void clearFurnitureSelection() {
    this.furnitureBrand.setText("");
    this.furnitureRef.setText("");
    this.furnitureLastIntervention.setDate(null);

    this.furnitureAction.setText("Ajout d'un matériel");
    this.furnitureButton.setText("Ajouter");

    this.furnitureSuppr.setEnabled(false);

    this.furnitureClient.setSelectedIndex(-1);
    this.furnituresList.clearSelection();
  }

  private void clearInterventionSelection() {
    this.interventionAnnotations.setText("");
    this.interventionCost.setText("");

    this.interventionBegin.setDate(null);
    this.interventionEnd.setDate(null);

    this.interventionType.setSelectedIndex(-1);
    this.interventionEmployee.setSelectedIndex(-1);
    this.interventionClient.setSelectedIndex(-1);

    this.interventionAction.setText("Ajout d'une intervention");
    this.interventionButton.setText("Ajouter");
    this.interventionSuppr.setEnabled(false);

    this.interventionsList.clearSelection();
  }

  private void fillList(List list, JList jlist) {
    DefaultListModel model = (DefaultListModel) jlist.getModel();
    model.clear();

    for (Object o : list) {
      model.addElement(o);
    }
  }

  private Boolean isInt(String val) {
    try {
      Integer.parseInt(val);
      return true;
    } catch (NumberFormatException e) {
      return false;
    }
  }

  /**
  * @param args the command line arguments
  */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Home().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel ClientTab;
  private javax.swing.JPanel EmployeeTab;
  private javax.swing.JPanel FurnitureTab;
  private javax.swing.JPanel InterventionTab;
  private javax.swing.JTabbedPane PieceTab;
  private javax.swing.JButton cancelClient;
  private javax.swing.JLabel clientAction;
  private javax.swing.JTextField clientAddress;
  private javax.swing.JButton clientButton;
  private javax.swing.JTextField clientFirstName;
  private javax.swing.JTextField clientLastName;
  private javax.swing.JButton clientSuppr;
  private javax.swing.JList clientsList;
  private javax.swing.JLabel employeeAction;
  private javax.swing.JTextField employeeAddress;
  private com.toedter.calendar.JDateChooser employeeBirthDate;
  private javax.swing.JButton employeeButton;
  private javax.swing.JButton employeeCancel;
  private javax.swing.JTextField employeeFirstName;
  private javax.swing.JTextField employeeName;
  private javax.swing.JComboBox employeeRole;
  private javax.swing.JTextField employeeSpe;
  private javax.swing.JButton employeeSuppr;
  private javax.swing.JList employeesList;
  private javax.swing.JLabel furnitureAction;
  private javax.swing.JTextField furnitureBrand;
  private javax.swing.JButton furnitureButton;
  private javax.swing.JButton furnitureCancel;
  private javax.swing.JComboBox furnitureClient;
  private com.toedter.calendar.JDateChooser furnitureLastIntervention;
  private javax.swing.JTextField furnitureRef;
  private javax.swing.JButton furnitureSuppr;
  private javax.swing.JList furnituresList;
  private javax.swing.JLabel interventionAction;
  private javax.swing.JTextArea interventionAnnotations;
  private com.toedter.calendar.JDateChooser interventionBegin;
  private javax.swing.JButton interventionButton;
  private javax.swing.JButton interventionCancel;
  private javax.swing.JComboBox interventionClient;
  private javax.swing.JTextField interventionCost;
  private javax.swing.JComboBox interventionEmployee;
  private com.toedter.calendar.JDateChooser interventionEnd;
  private javax.swing.JButton interventionSuppr;
  private javax.swing.JComboBox interventionType;
  private javax.swing.JList interventionsList;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel22;
  private javax.swing.JLabel jLabel23;
  private javax.swing.JLabel jLabel24;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JScrollPane jScrollPane5;
  // End of variables declaration//GEN-END:variables

}
