/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home.java
 *
 * Created on 5 févr. 2011, 18:26:20
 */

package org.meditenance.centre.ui;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.meditenance.centre.DAO.ClientDAO;
import org.meditenance.centre.DAO.EmployeeDAO;
import org.meditenance.centre.DAO.model.DAO;
import org.meditenance.centre.DAO.model.FurnitureDAO;
import org.meditenance.centre.DAO.model.InterventionDAO;
import org.meditenance.centre.DAO.model.PieceDAO;
import org.meditenance.centre.domain.Client;

/**
 *
 * @author Talus
 */
public class Home extends javax.swing.JFrame {
  // -- DAOs
  private DAO clientDAO = new ClientDAO();
  private DAO employeeDAO = new EmployeeDAO();
  private InterventionDAO interventionDAO = new org.meditenance.centre.DAO.InterventionDAO();
  private FurnitureDAO furnitureDAO = new org.meditenance.centre.DAO.FurnitureDAO();
  private PieceDAO pieceDAO = new org.meditenance.centre.DAO.PieceDAO();

  /** Creates new form Home */
  public Home() {
    this.initComponents();

    this.clientsList.setModel(new DefaultListModel());
    this.fillClientList(this.clientDAO.getAll());
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    TabbedPane = new javax.swing.JTabbedPane();
    ClientTab = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    clientsList = new javax.swing.JList();
    clientAction = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    clientLastName = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    clientFirstName = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    clientAddress = new javax.swing.JTextField();
    clientButton = new javax.swing.JButton();
    cancelClient = new javax.swing.JButton();
    clientSuppr = new javax.swing.JButton();
    FurnitureTab = new javax.swing.JPanel();
    EmployeeTab = new javax.swing.JPanel();
    InterventionTab = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(503, 458));
    setName("UI"); // NOI18N
    setResizable(false);

    TabbedPane.setName("TabbedPane"); // NOI18N

    ClientTab.setMinimumSize(new java.awt.Dimension(498, 430));
    ClientTab.setName("ClientTab"); // NOI18N

    jLabel1.setText("Clients");
    jLabel1.setName("jLabel1"); // NOI18N

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    clientsList.setName("clientsList"); // NOI18N
    clientsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        clientsListValueChanged(evt);
      }
    });
    jScrollPane1.setViewportView(clientsList);

    clientAction.setText("Ajout d'un Client");
    clientAction.setName("clientAction"); // NOI18N

    jLabel3.setText("Nom");
    jLabel3.setName("jLabel3"); // NOI18N

    clientLastName.setName("clientLastName"); // NOI18N

    jLabel4.setText("Prénom");
    jLabel4.setName("jLabel4"); // NOI18N

    clientFirstName.setName("clientFirstName"); // NOI18N

    jLabel5.setText("Addresse");
    jLabel5.setName("jLabel5"); // NOI18N

    clientAddress.setName("clientAddress"); // NOI18N

    clientButton.setText("Ajouter");
    clientButton.setName("clientButton"); // NOI18N
    clientButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clientButtonActionPerformed(evt);
      }
    });

    cancelClient.setText("Annuler");
    cancelClient.setName("cancelClient"); // NOI18N
    cancelClient.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelClientActionPerformed(evt);
      }
    });

    clientSuppr.setText("Supprimer");
    clientSuppr.setEnabled(false);
    clientSuppr.setName("clientSuppr"); // NOI18N
    clientSuppr.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clientSupprActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout ClientTabLayout = new javax.swing.GroupLayout(ClientTab);
    ClientTab.setLayout(ClientTabLayout);
    ClientTabLayout.setHorizontalGroup(
      ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ClientTabLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(6, 6, 6)
        .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(ClientTabLayout.createSequentialGroup()
            .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(ClientTabLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(clientAction))
              .addGroup(ClientTabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel4)
                  .addComponent(jLabel3)
                  .addComponent(jLabel5))))
            .addGap(6, 6, 6))
          .addGroup(ClientTabLayout.createSequentialGroup()
            .addComponent(cancelClient)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
        .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ClientTabLayout.createSequentialGroup()
            .addComponent(clientSuppr)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(clientButton))
          .addComponent(clientAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
          .addComponent(clientLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
          .addComponent(clientFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        .addGap(32, 32, 32))
    );
    ClientTabLayout.setVerticalGroup(
      ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ClientTabLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(clientAction))
        .addGap(18, 18, 18)
        .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(ClientTabLayout.createSequentialGroup()
            .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(clientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3))
            .addGap(33, 33, 33)
            .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(clientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel4))
            .addGap(29, 29, 29)
            .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(clientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel5))
            .addGap(42, 42, 42)
            .addGroup(ClientTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(clientSuppr)
              .addComponent(cancelClient)
              .addComponent(clientButton)))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(174, 174, 174))
    );

    TabbedPane.addTab("Clients", ClientTab);

    FurnitureTab.setName("FurnitureTab"); // NOI18N

    javax.swing.GroupLayout FurnitureTabLayout = new javax.swing.GroupLayout(FurnitureTab);
    FurnitureTab.setLayout(FurnitureTabLayout);
    FurnitureTabLayout.setHorizontalGroup(
      FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 498, Short.MAX_VALUE)
    );
    FurnitureTabLayout.setVerticalGroup(
      FurnitureTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 430, Short.MAX_VALUE)
    );

    TabbedPane.addTab("Matériel", FurnitureTab);

    EmployeeTab.setName("EmployeeTab"); // NOI18N

    javax.swing.GroupLayout EmployeeTabLayout = new javax.swing.GroupLayout(EmployeeTab);
    EmployeeTab.setLayout(EmployeeTabLayout);
    EmployeeTabLayout.setHorizontalGroup(
      EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 498, Short.MAX_VALUE)
    );
    EmployeeTabLayout.setVerticalGroup(
      EmployeeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 430, Short.MAX_VALUE)
    );

    TabbedPane.addTab("Employés", EmployeeTab);

    InterventionTab.setName("InterventionTab"); // NOI18N

    javax.swing.GroupLayout InterventionTabLayout = new javax.swing.GroupLayout(InterventionTab);
    InterventionTab.setLayout(InterventionTabLayout);
    InterventionTabLayout.setHorizontalGroup(
      InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 498, Short.MAX_VALUE)
    );
    InterventionTabLayout.setVerticalGroup(
      InterventionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 430, Short.MAX_VALUE)
    );

    TabbedPane.addTab("Interventions", InterventionTab);

    TabbedPane.setSelectedComponent(ClientTab);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(TabbedPane)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(TabbedPane)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cancelClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelClientActionPerformed
    this.clearClientSelection();
}//GEN-LAST:event_cancelClientActionPerformed

  private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
    Client cli = null;

    if (this.clientLastName.getText().isEmpty() || this.clientFirstName.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Les champs pour le nom et le prénom du client sont obligatoires", "Erreur", JOptionPane.ERROR_MESSAGE);
      return;
    }

    cli = this.clientSuppr.isEnabled() ? (Client) this.clientsList.getSelectedValue() : new Client();

    cli.setFirstName(this.clientFirstName.getText());
    cli.setLastName(this.clientLastName.getText());
    cli.setAddress(this.clientAddress.getText());

    this.clientDAO.save(cli);
    this.clearClientSelection();
    this.fillClientList(this.clientDAO.getAll());

    return;
}//GEN-LAST:event_clientButtonActionPerformed

  private void clientsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_clientsListValueChanged
    Client c = (Client) this.clientsList.getSelectedValue();

    if (c != null) {
      this.clientSuppr.setEnabled(true);

      this.clientAddress.setText(c.getAddress());
      this.clientFirstName.setText(c.getFirstName());
      this.clientLastName.setText(c.getLastName());

      this.clientAction.setText("Edition du client n°" + c.getId());
      this.clientButton.setText("Editer");
    }
}//GEN-LAST:event_clientsListValueChanged

  private void clientSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientSupprActionPerformed
    Client c = (Client) this.clientsList.getSelectedValue();

    if (c != null && JOptionPane.showConfirmDialog(this, "Êtes vous sur de supprimer le Client " + c + " ?", "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
      this.clientDAO.remove(c);
      this.clearClientSelection();
      this.fillClientList(this.clientDAO.getAll());
    }
  }//GEN-LAST:event_clientSupprActionPerformed

  private void clearClientSelection() {
    this.clientAddress.setText("");
    this.clientLastName.setText("");
    this.clientFirstName.setText("");

    this.clientAction.setText("Ajouter un client");
    this.clientButton.setText("Ajouter");
    this.clientSuppr.setEnabled(false);

    this.clientsList.clearSelection();
  }

  private void fillClientList(List<Client> list) {
    DefaultListModel model = (DefaultListModel) this.clientsList.getModel();
    model.clear();

    for (Client cli : list) {
      model.addElement(cli);
    }
  }

  /**
  * @param args the command line arguments
  */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Home().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel ClientTab;
  private javax.swing.JPanel EmployeeTab;
  private javax.swing.JPanel FurnitureTab;
  private javax.swing.JPanel InterventionTab;
  private javax.swing.JTabbedPane TabbedPane;
  private javax.swing.JButton cancelClient;
  private javax.swing.JLabel clientAction;
  private javax.swing.JTextField clientAddress;
  private javax.swing.JButton clientButton;
  private javax.swing.JTextField clientFirstName;
  private javax.swing.JTextField clientLastName;
  private javax.swing.JButton clientSuppr;
  private javax.swing.JList clientsList;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables

}
